# Generated by Django 5.0.6 on 2024-08-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='related_notes',
            field=models.ManyToManyField(blank=True, null=True, to='notes.note'),
        ),
    ]
